# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://wonderzhou.github.io
date_format: "ordinal"
title: hiscode
subtitle: "My git pages"
description: "周琦的个人博客"
keywords: hiscode, zhouqi, wonderzhou
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: wonderzhou
github_username: wonderzhou
location: ShenZhen, China
email: Jacky0902000@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wonderzhou/wonderzhou.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie
comments_provider: netease_gentie
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
disqus_username: wonderzhou
netease_gentie_key: e4944be0659247ae903d6ab6516d2746
# 在使用网易云跟帖时可点击显示 Disqus
lazy_load_disqus : true

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 
